print("hello world!")
print("Hello Again.")
print("I like typing this.")
print("This is fun.")
print("Yay! Printing.")
print("I'd rather you 'not'.")
print('I "said" do not touch this.')
print('This is another line.')
